### ISSUE TITLE
rc.d startup scripts not being generated

### ISSUE THREAD

**Issue by TheOnlyMunk** [tprelog/iocage-homeassistant#7] opened 2020-01-13 17:43 UTC
*appdaemon, homeassistant, and configurator* does not exist in /etc/rc.d or the local startup directories (***) or is not executable

Can I fix manually?

**Comment by TheOnlyMunk** [comment] 2020-01-13 17:58
`Installing setuptools, pip, wheel...

  Complete output from command /srv/configurator/bin/python3.7 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 21, in <module>
  File "/srv/configurator/lib/python3.7/tempfile.py", line 538, in NamedTemporaryFile
    prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
  File "/srv/configurator/lib/python3.7/tempfile.py", line 126, in _sanitize_params
    dir = gettempdir()
  File "/srv/configurator/lib/python3.7/tempfile.py", line 294, in gettempdir
    tempdir = _get_default_tempdir()
  File "/srv/configurator/lib/python3.7/tempfile.py", line 229, in _get_default_tempdir
    dirlist)
FileNotFoundError: [Errno 2] No usable temporary directory found in ['/tmp', '/var/tmp', '                            /usr/tmp', '/']
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 870, in main
    symlink=options.symlink,
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 1179, in create_enviro                            nment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 1023, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 1116, in _install_whee                            l_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/usr/local/lib/python3.7/site-packages/virtualenv.py", line 963, in call_subproces                            s
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode)                            )
OSError: Command /srv/configurator/bin/python3.7 - setuptools pip wheel failed with error                             code 1
_: line 2: /srv/configurator/bin/activate: No such file or directory



 Status Report:

      appdaemon does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d), or is not executable
  homeassistant does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d), or is not executable
   configurator does not exist in /etc/rc.d or the local startup
directories (/usr/local/etc/rc.d), or is not executable

 Home Assistant: http://192.168.0.25:8123
   HA Dashboard: http://192.168.0.25:5050
   Configurator: http://192.168.0.25:3218


Initial Startup Can Take 5-10 Minutes Before Home Assistant is Reachable
`

**Comment by tprelog** [comment] 2020-01-13 18:16
Yes I can help you directly download the files to the correct location but I suspect _none_ of the files in the overlay folder have been copied into place.

Can you please tell me what steps you used to install this? (I apologize, there are some slight differences between each, depending on if you used the 11.2 or 11.3 install script) You are the second person to not have the files from the overlay folder copied into place correctly. I am trying to narrow down the cause of this issue.

I suspect you are using FreeNAS 11.3 with [this most updated version](https://github.com/tprelog/iocage-homeassistant/tree/11.3-RELEASE) of the Home Assistant script?

**Comment by TheOnlyMunk** [comment] 2020-01-13 18:45
> Yes I can help you directly download the files to the correct location but I suspect _none_ of the files in the overlay folder have been copied into place.
> 
> Can you please tell me what steps you used to install this? (I apologize, there are some slight differences between each, depending on if you used the 11.2 or 11.3 install script) You are the second person to not have the files from the overlay folder copied into place correctly. I am trying to narrow down the cause of this issue.
> 
> I suspect you are using FreeNAS 11.3 with [this most updated version](https://github.com/tprelog/iocage-homeassistant/tree/11.3-RELEASE) of the Home Assistant script?

Freenas 11.2u7 - followed the exact steps described, except as root so did not use sudo

**Comment by tprelog** [comment] 2020-01-13 18:52
Ok so standard jail scripted install on FreeNAS 11.2-U7 got it

>  followed the exact steps described

Yes but which directions? I'm assuming you mean from the README when you clicked on this repository? That would be the master branch. I need to be sure because the instructions are different depending on which branch of my repository you are using. Sorry for the confusion

**Comment by TheOnlyMunk** [comment] 2020-01-13 18:57
> Ok so standard jail scripted install on FreeNAS 11.2-U7 got it
> 
> > followed the exact steps described
> 
> Yes but which directions? I'm assuming you mean from the README when you clicked on this repository? That would be the master branch. I need to be sure because the instructions are different depending on which branch of my repository you are using. Sorry for the confusion

Yes the readme from master

**Comment by tprelog** [comment] 2020-01-13 19:00
Perfect thanks! I running through a test install now.

Last thing I forgot to ask. How did you answer the questions? It seems you were expecting all 3 application so I assume you answered yes to all four questions? Can you please verify
```
Install Home-Assistant?  [Y/n]:
Install Hass-Configurator?  [Y/n]:
App-Daemon & HA-Dashboard?  [Y/n]:
Use the pre-configured examples?  [Y/n]:
```

**Comment by TheOnlyMunk** [comment] 2020-01-13 19:06
> Perfect thanks! I running through a test install now.
> 
> Last thing I forgot to ask. How did you answer the questions? It seems you were expecting all 3 application so I assume you answered yes to all four questions? Can you please verify
> 
> ```
> Install Home-Assistant?  [Y/n]:
> Install Hass-Configurator?  [Y/n]:
> App-Daemon & HA-Dashboard?  [Y/n]:
> Use the pre-configured examples?  [Y/n]:
> ```

yes, answers yes to all 4

**Comment by tprelog** [comment] 2020-01-13 20:55
So the 1st issue is appdaemon 4.0.0 has some additional configuration options now required. I will set these to some generic defaults in my example config but they will need to be changed to your specific local.

```
  latitude:
  longitude:
  elevation: 
  time_zone:
```
I did some testing, aside from the appdaemon issue mentioned, I do not get any of the errors you got. Home Assistant and Configurator both installed and were running --- So first option I could still help you download and place everything to your existing install but based on the full output  (It looks like configurator is not even installed) you shared it may require some trial and error to get everything to work. I'm still trying to work out a troubleshooting procedure when things don't work properly. A fresh install with everything is only about 10-15 min. Usually if your just getting started it is simply quicker to try reinstalling rather than troubleshooting.

The quickest answer is going to be reinstalling using the updated script. This will install an 11.3-RELEASE jail but according to people in the FreeNAS forums, this is OK on FreeNAS 11.2-U7 or later.

First you should fetch the 11.3-RELEASE from the FreeNAS console
```
iocage fetch
```
Select 11.3 from the menu and let it download and extract.

I'm running HA as a plugin-jail on FreeNAS 11.3 and it is now my first choice. Right now this most tested and (I think) should provide the best experience. Not all of the updates here have made there way back to the standard-jail. To install this using the updated script.
```
wget -O /tmp/pkglist.json https://raw.githubusercontent.com/tprelog/freenas-plugin-index/11.3-RELEASE/homeassistant.json
iocage fetch -P dhcp=on bpf=yes vnet=on boot=on allow_raw_sockets=1 -n /tmp/pkglist.json --branch 11.3-RELEASE
```
This will give you the updated console menu. After your initial login to HA, you can use the console menu to install the configurator and appdaemon (and HACS but you need to type in this command) (and ESPHome but that still needs a little work so hold off on that one for a day or two)

---

If you would rather have the standard-jail you can still use the updated 11.3 script
```
echo '{"pkgs":["autoconf","bash","ca_root_nss","git-lite","gmake","pkgconf","python37","py37-sqlite3"]}' > /tmp/pkglist.json
iocage create -r 11.3-RELEASE dhcp=on bpf=yes vnet=on boot=on allow_raw_sockets=1 -p /tmp/pkglist.json -n homeassistant
iocage exec homeassistant git clone -b 11.3-RELEASE https://github.com/tprelog/iocage-homeassistant.git /root/.iocage-homeassistant
iocage exec homeassistant bash /root/.iocage-homeassistant/post_install.sh standard
```
Answer the question like this (Say NO to appdaemon)
```
Install Home Assistant?  [Y/n]: Y
Install Hass Configurator?  [Y/n]:Y 
App-Daemon & HA-Dashboard?  [Y/n]: N
Use the pre-configured examples?  [Y/n]Y
```
Don't worry you can still install appdaemon after Home Assistant is running.
I recommend this order because appdaemon will produce a login error every 5 seconds until a long-lived-access-token is created.  I suggest you create the token for appdaemon and add it to the Home Assistant secretes file _before_ you install appdaemon.

There's no console menu in the standard-jail but you can still easily install appdaemon after you have created the long live token
```
iocage console homeassistant
./post_install.sh appdaemon
```

Besides the console menu, the biggest change are the updated rc.d service scripts. In the  11.3-RELEASE, they now have some additional functions

In Home Assistant only
```
service homeassistant check_config
```
They all have `upgrade` and `test`
```
service homeassistant upgrade
service appdaemon test
``` 

Upgrade is what it is. Upgrade the application to the newest version
Test will just check the virtualenv, tell what version of python is used and check if the main (homeassistant, appdaemon, configurator) application is installed. If it's installed it will report the version of that as well

**Comment by TheOnlyMunk** [comment] 2020-01-14 16:36
Thanks - seems like I got further wit the first 11.3 suggestion - at least it installed without errors and I was able to setup and create a user without errors.

**Comment by tprelog** [comment] 2020-01-14 17:55
Great is running! Sorry for the troubles you had.

Hopefully by this weekend the 11.3-RELEASE will become the default branch for this repo.

I will suggest the plugin-jail is only for anyone using FreeNAS 11.3

The 11.3-RELEASE standard-jail will be the suggested install for anyone using FreeNAS 11.2-U7 or later. 

This will also be suggested for FreeNAS 11.3 if you want to change my default system settings. Basically if you want to make changes to the jail's *BSD system itself.

With regards to Home Assistant an the other application running in virtualenvs, there is no difference between the plugin-jail and the standard-jail.

**Comment by tprelog** [comment] 2020-02-06 23:24
I'm gonna close this issue. The configuration files have all been updated and this can now be installed from the FreeNAS 11.3 community plugins. If you have any further problems please open a new issue

**Closed by tprelog** 2020-02-06 23:24 UTC
