### ISSUE TITLE
HomeKit integration not working (ChaCha20Poly1305 not supported)

### ISSUE THREAD

**Issue by itavero** [tprelog/iocage-homeassistant#14] opened 2020-04-30 20:47 UTC
I tried to enable HomeKit within Home Assistant (by adding `homekit:` to the `configuration.yaml`).
Unfortunately it appears that the jail does not have the right cryptography algorithms available.

When trying to pair, the log of home assistant shows:
```
2020-04-30 22:39:40 INFO (Thread-5) [pyhap.hap_server] 10.10.11.104 - "POST /pair-setup HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('10.10.11.104', 57324)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/srv/homeassistant/lib/python3.7/site-packages/pyhap/hap_server.py", line 892, in finish_request
    self, self.accessory_handler)
  File "/srv/homeassistant/lib/python3.7/site-packages/pyhap/hap_server.py", line 163, in __init__
    super(HAPServerHandler, self).__init__(sock, client_addr, server)
  File "/usr/local/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/srv/homeassistant/lib/python3.7/site-packages/pyhap/hap_server.py", line 239, in dispatch
    getattr(self, self.HANDLERS[self.command][path])()
  File "/srv/homeassistant/lib/python3.7/site-packages/pyhap/hap_server.py", line 264, in handle_pairing
    self._pairing_three(tlv_objects)
  File "/srv/homeassistant/lib/python3.7/site-packages/pyhap/hap_server.py", line 328, in _pairing_three
    cipher = ChaCha20Poly1305(hkdf_enc_key)
  File "/srv/homeassistant/lib/python3.7/site-packages/cryptography/hazmat/primitives/ciphers/aead.py", line 21, in __init__
    exceptions._Reasons.UNSUPPORTED_CIPHER
cryptography.exceptions.UnsupportedAlgorithm: ChaCha20Poly1305 is not supported by this version of OpenSSL
----------------------------------------
```

(Also see home-assistant/core#34130, I guess)

**Comment by RafalLukawiecki** [comment] 2020-05-17 16:36
I just run into the same issue. First of all, that algorithm is not supported by openssl 1.0.2s-freebsd which would be the default in /usr/bin/openssl. This can be fixed by installing a more current version of openssl from ports, say `pkg install openssl` will get us 1.1.1g.

Unfortunately, the next issue will be that of a PATH. By default, /usr/local/bin is later in path order, so the old openssl gets loaded by the script. I have tried modifying the rc.d/homeassistant script but I have failed. Then I realised the script uses `sh` to start `hass` using the `hass` username. I created a `.profile` in `/home/hass` containing an `export PATH=/usr/local/sbin:/usr/local/bin:$PATH". This had the effect of supressing the above error message. I assume that the correct version of openssl is being used now—but I cannot be sure.

Unfortunately, I still get the error in the Home app that the Home Assistant accessory cannot be added. I have not debugged it any further yet—hoping others have more info.

**Comment by notthatwillsmith** [comment] 2020-05-20 02:58
I'm having the same problem using the plugin version of Home Assistant on 11.3. I tried messing with the path, but couldn't  get it working.

**Comment by tprelog** [comment] 2020-05-22 19:44
It boils down to this
>HomeKit requires openssl 1.1.0 or later as the HomeKit Accessory Protocol (HAP) uses the ChaCha20 stream cipher and the Poly1305 authenticator.

The problem is [the 11.3-RELEASE base only contains openssl 1.0.2.](https://wiki.freebsd.org/OpenSSL)

There is a [related thread in the FreeNAS forums](https://www.ixsystems.com/community/threads/openssl-update-to-1-1-1.76814/) with a marked solution but as this requires compiling packages from the ports tree, I am unsure how to apply this to Home Assistant.

**Comment by RafalLukawiecki** [comment] 2020-05-22 20:13
Thanks for sharing this @tprelog, however, it is straightforward to install a newer OpenSSL using ports/pkg **inside** the jail. You do not need to have a newer one outside of it. Once installed, the key issue that remains is that the PATH order will still present the old one in /usr/bin before the newer one, in /usr/local/bin. This can be solved by changing the PATH as I have shown above. At that stage I could see the new one was being used by HA, but there were additional issues, unrelated to the version of OpenSSL, which I failed to debug. So unless I am missing something else, the issue is not just the version of OpenSSL but something additional to that.

**Comment by julianpomper** [comment] 2020-05-23 07:38
I have the same problem on 11.3 with HA 0.110.1. Could not find a solution either.

**Comment by tprelog** [comment] 2020-05-23 21:13
**Thank you @RafalLukawiecki for providing the keys to this _possible solution!_** I _might_ have found the missing piece. I don't have any physical HomeKit devices to test with -- but with the following steps I was successfully able to pair the `HomeKit Bridge` integration with the `HomeKit Controller` integration.

I'm sorry I can't test this any further but I hope this is the solution we are looking for.

```
2020-05-23 16:03:45 INFO (Thread-3) [pyhap.hap_server] Got connection with ('10.10.1.227', 14517).
2020-05-23 16:03:45 INFO (Thread-4) [pyhap.hap_server] 10.10.1.227 - "POST /pair-setup HTTP/1.1" 200 -
2020-05-23 16:03:51 INFO (Thread-4) [pyhap.hap_server] 10.10.1.227 - "POST /pair-setup HTTP/1.1" 200 -
2020-05-23 16:03:51 INFO (Thread-4) [pyhap.accessory_driver] Paired with 45a837b0-9ed3-42ec-9ac0-ac8485ec989e.
2020-05-23 16:03:51 INFO (Thread-4) [pyhap.hap_server] 10.10.1.227 - "POST /pair-setup HTTP/1.1" 200 -
2020-05-23 16:03:51 INFO (Thread-3) [pyhap.hap_server] Got connection with ('10.10.1.227', 54554).
2020-05-23 16:03:51 INFO (Thread-5) [pyhap.hap_server] 10.10.1.227 - "POST /pair-verify HTTP/1.1" 200 -
2020-05-23 16:03:51 INFO (Thread-5) [pyhap.hap_server] 10.10.1.227 - "POST /pair-verify HTTP/1.1" 200 -
2020-05-23 16:03:51 INFO (Thread-5) [pyhap.hap_server] 10.10.1.227 - "GET /accessories HTTP/1.1" 200 -
2020-05-23 16:03:51 INFO (MainThread) [homeassistant.setup] Setting up homekit_controller
2020-05-23 16:03:51 INFO (MainThread) [homeassistant.setup] Setup of domain homekit_controller took 0.0 seconds.
2020-05-23 16:03:52 INFO (Thread-3) [pyhap.hap_server] Got connection with ('10.10.1.227', 45375).
2020-05-23 16:03:52 INFO (Thread-6) [pyhap.hap_server] 10.10.1.227 - "POST /pair-verify HTTP/1.1" 200 -
2020-05-23 16:03:52 INFO (Thread-6) [pyhap.hap_server] 10.10.1.227 - "POST /pair-verify HTTP/1.1" 200 -
2020-05-23 16:03:52 INFO (Thread-6) [pyhap.hap_server] 10.10.1.227 - "GET /accessories HTTP/1.1" 200 -
```


---

Connect to the jail console, stop the homeassistant service, then install the updated openssl
```bash
iocage console $HA_JAIL
# Press `0` to exit to the console
pkg install -y openssl
service homeassistant stop
```

Switch to the user `hass` and create a `.profile` in hass the home directory
```bash
su - hass
ee .profile
```

Add the following lines to `.profile`
```
export PATH="/usr/local/sbin:/usr/local/bin:${PATH}"
export CFLAGS=-I/usr/local/include/
export LDFLAGS=-I/usr/local/include/
```

The user `hass` needs to logout / login again to apply these changes
```bash
exit
su - hass
```

Now a quick check to make sure we have the updated openssl
```bash
openssl version

## output
OpenSSL 1.1.1g  21 Apr 2020
```

Next we need delete the `.cache` directory
```bash
rm -rf .cache
```

Finally, still as user `hass`, we need activate the virtualenv and reinstall homeassistant so it will use the updated openssl
```bash
source /srv/homeassistant/bin/activate
pip install --force-reinstall homeassistant
deactivate && exit
```

Start the homeassistant service
```bash
service homeassistant start
```

Try again to use HomeKit

**Comment by tprelog** [comment] 2020-05-24 13:43
If any body can confirm this works I'll add the changes to the FN plugin. Thanks

**Comment by RafalLukawiecki** [comment] 2020-05-24 13:44
I am working on my OpenHAB set-up this weekend, but I plan on testing your fix—if not today, then this week. Many thanks for the fix, I will report back.

**Comment by julianpomper** [comment] 2020-05-24 13:46
It is now working for me 👌🏻

**Comment by pixel8383** [comment] 2020-05-25 11:14
I was able to install OpenSSL 1.1.1 as suggested by @tprelog but during the re-installation I got the following issues:

```
ERROR: python-jose-cryptodome 1.3.2 has requirement pycryptodome<3.4.0,>=3.3.1, but you'll have pycryptodome 3.9.6 which is incompatible.
ERROR: pyipp 0.10.1 has requirement aiohttp==3.6.2, but you'll have aiohttp 3.6.1 which is incompatible.
ERROR: aiohomekit 0.2.37 has requirement zeroconf[ip]<0.25.0,>=0.24.4, but you'll have zeroconf 0.26.1 which is incompatible.
```

And inside the logger I got this:


```
Logger: homeassistant.setup
Source: setup.py:139

    Setup failed for cloud: Unable to import component: /usr/local/share/homeassistant/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: Undefined symbol "OPENSSL_no_config"
    Setup failed for mobile_app: Unable to import component: /usr/local/share/homeassistant/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: Undefined symbol "OPENSSL_no_config"
    Setup failed for homekit: Unable to import component: /usr/local/share/homeassistant/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: Undefined symbol "OPENSSL_no_config"
```

**Comment by pixel8383** [comment] 2020-05-25 13:47
Ok, I tried once again. I rolled back the jail to homeassistant 0.110.0, then tried with stop homeassistant service and install openssl.

I then logged into homeassistant user console and checked the OpenSSL version (it was OpenSSL 1.1.1g  21 Apr 2020).

As per @tprelog suggestion I updated the profile for that user and logged out and in again.

I forced an upgrade (well, actually an update was due since the v0.110.2 was out) but during the installation I got the following errors:

``
ERROR: python-jose-cryptodome 1.3.2 has requirement pycryptodome<3.4.0,>=3.3.1, but you'll have pycryptodome 3.9.6 which is incompatible.
ERROR: pyipp 0.10.1 has requirement aiohttp==3.6.2, but you'll have aiohttp 3.6.1 which is incompatible.
ERROR: hass-nabucasa 0.34.2 has requirement pytz~=2019.3, but you'll have pytz 2020.1 which is incompatible.
ERROR: aiohomekit 0.2.37 has requirement zeroconf[ip]<0.25.0,>=0.24.4, but you'll have zeroconf 0.26.1 which is incompatible.
``

Anyhow, the installation was completed and I was able to pair once againt HomeAssistant with HomeKit.

I am actually worried about those errors: I am not sure what will not be working fine (expecially for first 2 and last error line).

**Comment by tprelog** [comment] 2020-05-25 13:59
@pixel8383 


```
ERROR: python-jose-cryptodome 1.3.2 has requirement pycryptodome<3.4.0,>=3.3.1, but you'll have pycryptodome 3.9.6 which is incompatible.
ERROR: pyipp 0.10.1 has requirement aiohttp==3.6.2, but you'll have aiohttp 3.6.1 which is incompatible.
ERROR: hass-nabucasa 0.34.2 has requirement pytz~=2019.3, but you'll have pytz 2020.1 which is incompatible.
ERROR: aiohomekit 0.2.37 has requirement zeroconf[ip]<0.25.0,>=0.24.4, but you'll have zeroconf 0.26.1 which is incompatible.
```

For these error, as long as the upgrade or reinstall say it completed,  just ignore them for now. I just did a new install on the plugin this morning with `0.110.2` and then immediately applied the openssl fix to the clean install. I received a similar error, I haven't tracked down the reason yet but at this point I don't think it's anything directly related to using the "FreeNAS Plugin" ( I also have HA in a completely manual jail and still have the same errors )

Also my production install has been running for some time now. I've seen these error before during normal HA upgrades .Sometime reporting incompatibility with old version of HA
```
ERROR: pyipp 0.10.1 has requirement aiohttp==3.6.2, but you'll have aiohttp 3.6.1 which is incompatible.
```

I'm trying to get some answers on discord now

**Comment by pixel8383** [comment] 2020-05-25 14:08
Sorry, I did not pointed out before: I am running HA inside a jail with manual installation (no plugin).

**Comment by notthatwillsmith** [comment] 2020-05-25 18:37
> **Thank you @RafalLukawiecki for providing the keys to this _possible solution!_** I _might_ have found the missing piece. I don't have any physical HomeKit devices to test with -- but with the following steps I was successfully able to pair the `HomeKit Bridge` integration with the `HomeKit Controller` integration.
> 

This fixed the problem for me.

**Comment by tprelog** [comment] 2020-05-26 23:18
The plugin is updated -- Any new installs should now have openssl-1.1.1 and HomeKit working out of the box.

To fix an existing install -- First "UPDATE" the plugin from the FreeNAS webui
![image](https://user-images.githubusercontent.com/35702532/82958816-504dd900-9f84-11ea-8f49-006d149e6424.png)

After the update, you will still need to reinstall the homeassistant virtualenv so it uses the updated openssl. Do this from the jail console -- I have added a new service command to assist

**To reinstall the current HA version you are running**
```
iocage console $_JAIL_NAME
# Press `0` to exit the menu
service homeassistant reinstall
```

**To reinstall using the latest (stable) release available**
```
iocage console $_JAIL_NAME
# Press `0` to exit the menu
service homeassistant reinstall upgrade
```

**To reinstall using a specific version**
For example HA 0.109.3
```
iocage console $_JAIL_NAME
# Press `0` to exit the menu
service homeassistant reinstall 0.109.3
```

**Comment by RafalLukawiecki** [comment] 2020-05-27 11:49
I am happy to report that the fix worked. I have installed a clean plugin using the most recent version and the HomeKit Bridge set-up without a hitch. Thank you for your work, @tprelog!

**Comment by tprelog** [comment] 2020-06-13 03:12
```
ERROR: python-jose-cryptodome 1.3.2 has requirement pycryptodome<3.4.0,>=3.3.1, but you'll have pycryptodome 3.9.6 which is incompatible.
ERROR: pyipp 0.10.1 has requirement aiohttp==3.6.2, but you'll have aiohttp 3.6.1 which is incompatible.
ERROR: hass-nabucasa 0.34.2 has requirement pytz~=2019.3, but you'll have pytz 2020.1 which is incompatible.
ERROR: aiohomekit 0.2.37 has requirement zeroconf[ip]<0.25.0,>=0.24.4, but you'll have zeroconf 0.26.1 which is incompatible.
```
> I am actually worried about those errors: I am not sure what will not be working fine (expecially for first 2 and last error line).

So just a follow up... these errors do in fact seem to be triggered from some previously installed versions of things -- The current solution I presented is using `pip install --force-reinstall homeassistant` rather than a true "clean install". If you'd like to try again without error, simply delete, then create a new venv before reinstalling Home Assistant against `openssl-1.1.1`

**Comment by tprelog** [comment] 2020-06-26 18:12
**The saga continues in the 11.3-RELEASE...**

I think I'm gonna have to revert the "out-of-the-box" update to openssl :disappointed: This solution ( in it's current state ) breaks the "out-of-the-box" working [ Z-Wave ( 1.4 ) integration](https://www.home-assistant.io/integrations/zwave/). 

There is another workaround to get Z-Wave working again but this workaround will need to applied aafter every update to `homeassistant-pyozw`. So now there are 2 workarounds and the seconds needs constant attention for all Z-Wave users... <s>I think</s> this is quickly turning into :hankey:

After consideration, I think it best that I remove the updated openssl from this plugin. The bottom line is, I do not want to by default, apply a  workaround or update something in this plugin, that will break something else, that would otherwise work if you followed a manual installation.

I'm going to submit another pull request to have openssl removed from the plugin manifest... If you have already installed openssl, it will not be removed unless done so manually. If your HomeKit is working today it should not be affected.

So one way or another, someone needs to apply a work around, the best I can do is try to minimize the effect. Moving forward on the 11.3-RELEASE community plugin, if you need to use the HomeKit integration, you will still be able to follow the steps needed to update openssl in a manual installation.
- If you update openssl for HomeKit and you _are **not** using_ the Z-Wave integration, this will be a one time manual intervention. 
- If you update openssl for HomeKit and you _are using_ the Z-Wave integration, you will need to manually apply both workarounds and will require manual intervention every time `homeassistant-pyozw` is updated

**The 12.x -RELEASES includes openssl 1.1.1. The HomeKit integration already works "out-of -the-box" in TrueNAS Core 12, _without any additional steps or workarounds_**

**Comment by tprelog** [comment] 2020-12-01 17:56
This plugin is no longer supported on **FreeNAS**

Plugins on TrueNAS CORE are currently based on FreeBSD 12.1-RELEASE, which include openssl 1.1.1 in the base system. HomeKit should already work as expected.

**Closed by tprelog** 2020-12-01 17:56 UTC
Labels: Fixed in 12.1-RELEASE
